[functions]
    directory = "functions"
[[redirects]]
    from = "/fetch-phone-numbers"
    to = "/.netlify/functions/fetchPhoneNumbers"
    status = 200
[[redirects]]
    from = "/update-phone-number"
    to = "/.netlify/functions/updatePhoneNumbersList"
    status = 200
[[redirects]]
    from = "/create-new-visiting-card"
    to = "/.netlify/functions/createNewCard"
    status = 200
[[redirects]]
    from = "/fetch-visiting-cards"
    to = "/.netlify/functions/getVisitingCards"
    status = 200
[[redirects]]
    from = "/fetch-specific-visiting-card"
    to = "/.netlify/functions/getSpecificVisitingCard"
    status = 200
[[redirects]]
    from = "/update-visiting-card"
    to = "/.netlify/functions/updateVisitingCard"
    status = 200
[[redirects]]
    from = "/delete-visiting-card"
    to = "/.netlify/functions/deleteVisitingCard"
    status = 200
